repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-isort>=4.0.0
          - flake8-comprehensions>=3.4.0
          - flake8-builtins>=1.5.3
          - flake8-docstrings>=1.6.0
          - flake8-bugbear>=21.3.2
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
      - id: python-bandit-vulnerability-check
        args: [-l, -x, "./tests", "."]
        files: .py$